version: '2'
services:
  bridge:
    container_name: pb_${PROTONMAIL_LOGIN}
    build:
      context: .
      args:
        PROTONMAIL_BRIDGE_VERSION: ${PROTONMAIL_BRIDGE_VERSION}
        SMTP_PORT: ${SMTP_PORT}
        IMAP_PORT: ${IMAP_PORT}
    environment:
      PROTONMAIL_LOGIN: ${PROTONMAIL_LOGIN}
      PROTONMAIL_PASSWORD: ${PROTONMAIL_PASSWORD}
      PROTONMAIL_EXTRA_2FA: ${PROTONMAIL_EXTRA_2FA}
      SMTP_PORT: ${SMTP_PORT}
      IMAP_PORT: ${IMAP_PORT}
    ports:
      - "${SMTP_PORT}:${SMTP_PORT}"
      - "${IMAP_PORT}:${IMAP_PORT}"
